# Site settings
title: Indospy.net
url: "http://indospy.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "http://indospy.github.io/isnet-backup/" 

#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: indo_spy@example.com
author: Indospy
avatar: "//www.gravatar.com/avatar/f62af6279c023349d8b55a0ad9ceefd6?d=mm&s=135"
profile: One sentence introducing yourself.
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /:title.html
gems:
 - jekyll-paginate 
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
